### ISSUE TITLE
Allow affected user to be specified when tracing an error

### ISSUE THREAD

**Issue by mariahlynne** [sirkirby/raygun.diagnostics#14]
Currently the affected user can be specified by setting the `Raygun.Diagnostics.Settings.Client.User` property, but this is a static property. It would be helpful to be able to specify a non-static affected user when tracing an error so that the error in Raygun lists the correct user.

**Comment by sirkirby** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;VgmQbLHJ&#x2F;3-add-ability-to-raygun-diagnostics-to-pass-a-user-object-through-to-raygun"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add ability to Raygun.Diagnostics to pass a user object through to Raygun</a>

**Comment by sirkirby** [comment]
Going to add support for this by recognizing a raygun user as a special argument, shown here https://github.com/sirkirby/raygun.diagnostics/blob/master/src/Raygun.Diagnostics/RaygunTraceListener.cs#L215

**Comment by sirkirby** [comment]
@mariahlynne This is the object we can use https://github.com/MindscapeHQ/raygun4net/blob/67c4bb9fd660afb91d62e9333d75a36a85ee5d4f/Mindscape.Raygun4Net/Messages/RaygunIdentifierMessage.cs

By passing that as an argument to the `TraceError` statement, the user will pass through to raygun with the proper tracking.

```c#
Trace.TraceError("something bad happend", new RaygunIdentifierMessage("sessionUserName") { Fullname = "John D", Email = "johnd@email.com", UUID = "customId") };
```

**Comment by sirkirby** [comment]
@mariahlynne check out the pull request and see if that will meet your needs.

**Comment by mariahlynne** [comment]
@sirkirby yes, this works very well. Thank you for getting this implemented so quickly!

**Comment by sirkirby** [comment]
I had a thought just after creating the PR. The whole point of this lib was to not necessarily tie you in to Raygun. With that in mind, I need to make one more change. I'll create a simple abstraction for User so that the calling application does not have to take dependency on Raygun. Something like:

```c#
public interface UserInfo
{
  string Id {get; set;}
  string Username {get; set;}
  string Fullname {get; set;}
  string Firstname {get; set;}
  string Email {get; set;}
}
```

**Comment by sirkirby** [comment]
I've got the above implemented along with a less dependent way to pass the info...I couldn't decide on what to keep, so we'l just do both. Can either implement that interface, use the built in UserInfo implementation from this lib, or pass in an anon type that the listener will identify as a user when you pass an object with a public username property. I just need to finish up the unit tests and then update the documentation.
