### ISSUE TITLE
Documentation suggests `AddRange` method is available upon `DefaultTags`

### ISSUE THREAD

**Issue by jpierson** [sirkirby/raygun.diagnostics#17]
Perhaps there has been a change in implementation of DefaultTags from `List` to `string[]` but regardless the example in README.md for how to set default tags doesn't seem to be compatable with the latest release on NuGet (1.1.0).
```
// add default tags to every message generated by app domain
Raygun.Diagnostics.Settings.DefaultTags.AddRange(new[] {"debug", "someDynamicString"});
```

**Comment by sirkirby** [comment]
@jpierson yes, I believe it was changed to an array, so the documentation is incorrect. We'll get that updated on the next release... or feel free to submit a PR
