### ISSUE TITLE
RaygunTraceListener sometimes causes infinite blocking on call to Trace.TraceError

### ISSUE THREAD

**Issue by jpierson** [sirkirby/raygun.diagnostics#20]
I've just run into an issue today where I noticed my application locking up on a call to `Trace.TraceError`. At first I assumed it was an issue with our own custom color console listener but after some investigation the culprit seems to be `RaygunTraceListener`. This is a multi-threaded console project application that is using _Mindscape.Raygun4Net v5.3.1_ and _Raygun.Diagnostics v1.2.0_. In this application Trace.TraceError is used successfully and at other times it does not and blocks the output so I'm guessing this may have to do with internal handling perhaps not being thread safe. It's also important to note that in particular places we can get Trace.TraceError to consistently hang each time.

**Comment by jpierson** [comment]
Here is a trace of the calls that I see when this happens.

![image](https://cloud.githubusercontent.com/assets/1467146/18590069/6dc3213a-7bfb-11e6-9a39-6312326884d6.png)

**Comment by jpierson** [comment]
Interesting. In my code I had a block like this where I was testing this issue.

_this blocks indefinitely for me_

```
Trace.TraceError("Error");
```

Based on the call stack that I pasted above I tried using the RaygunClient directly instead to send a message and when I added that line before the TraceError call not only did the call to Client.Send succeed but the call to Trace.TraceError also no longer hangs and I've verified that both messages make it to Raygun.

_this works without hanging_

```
Raygun.Diagnostics.Settings.Client.Send(ex);
Trace.TraceError("Error");
```

**Comment by jpierson** [comment]
Assuming that this may have something to do with the type of message that is sent to the Raygun client I attempted to formulate a similar message directly and send it like so.

```
var listener = Trace.Listeners.OfType<Raygun.Diagnostics.RaygunTraceListener>().Single();
var message = listener.MessageFromTraceEvent(null, "source", TraceEventType.Error, 1, "Error");
listener.WriteMessage(message);
```

This however worked with no problem and once again surprisingly any subsequent calls to TraceError also succeed without hangling. After a few itterations of this example to minimalize the effect I have the following which also succeeds.

```
var listener = Trace.Listeners.OfType<Raygun.Diagnostics.RaygunTraceListener>().Single();
var message = listener.MessageFromTraceEvent(null, "source", TraceEventType.Error, 1, "Error");
Trace.TraceError("Error");
```

The two notable things from above is that I didn't have to actually send a message but only to call the `MessageFromTraceEvent` method to change the undesirable hanging behavior of Trace.TraceError. Also note that I'm passing _null_ for the `TraceEventCache` parameter mainly just because I don't have access to it here and this may impact the behavior.

**Comment by jpierson** [comment]
The most recent test I've done just makes the behavior seem even more arbitrary which tells me that this may be a deeper issue.

_this also works without hanging_

```
var client = Raygun.Diagnostics.Settings.Client;
Trace.TraceError("Error");
```

Unfortunately I'm going to have to remove RaygunTraceListener from my projects until I can get this straightened out.

**Comment by sirkirby** [comment]
Hey @jpierson , sorry about the issue. Where are you setting your raygun key?

I've not been able to reproduce the blocking you are seeing, so the first thing that comes to mind is a configuration error. I also spent a few mins looking at mindscape's code for the raygun .NET provider. They are using WebClient.UploadString(), so it's possible that could block...though they have good error handling and fail back. What I did discover that was interesting, is a SendInBackground method on the RaygunClient...that offloads the Send() to a backround thread using QueueUserWorkItem. So by definition, that should not block the main thread. I'll look into supporting that as an option through the trace listener...it would be a nice option to have.

**Comment by sirkirby** [comment]
Another thought on the issue. Can you try adding a secondary listener? If the raygun trace listener sees another listener and an exception occurs within the code, it will push that exception to the other trace listener in your app.

**Comment by jpierson** [comment]
I did have a secondary listener stacked after RaygunTraceListener and that is how I found the issue originally. I was intentionally throwing an exception, catching it, and then tracing it but I wasn't seeing it get picked up in the trace listener. In my tests it doesn't appear that an exception happens it just blocks on the call to `Monitor.Enter` as shown above. Putting my custom trace listener before RaygunTraceListener at least allowed me to see those traces but then I still have the indefinitely hanging issue.

**Comment by jpierson** [comment]
I should add that it appears that this may be if anything pointing to an issue in the Raygun Client implementation or within the WebProxy implementation but since I don't yet have a way of reproducing a similar issue with either of those directly I'm unsure how to follow up there.

**Comment by sirkirby** [comment]
@jpierson what version of .NET are you targeting?

**Comment by jpierson** [comment]
.NET Framework 4.5.2

Relevant package dependencies:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Mindscape.Raygun4Net" version="5.3.1" targetFramework="net452" />
  <package id="Raygun.Diagnostics" version="1.2.0" targetFramework="net452" />
</packages>
```

**Comment by jpierson** [comment]
Hmmm, I'm no longer able to reproduce this issue :( The only significant thing I've done is uninstalled and reinstalled the Nuget packages for both the Raygun Client and the Raygun.Diagnostics. My concern however is that it may happen again in production.

**Comment by sirkirby** [comment]
Not surprised that a reinstall fixed it, that has happened to me many times with other libraries. 

For comparison, we are running about 20 apps in production with v1.2 and are not seeing the issue. But let's keep the issue open for a while just in case. I'll create a separate issue for adding background send support to the trace listener.
