### ISSUE TITLE
No evidence of logging

### ISSUE THREAD

**Issue by jpierson** [sirkirby/raygun.diagnostics#9]
I've added Raygun.Diagnostics (v 0.7.3.0) package reference in my windows service project using nuget. I've modified my app.config so that it looks like the example below.

    <system.diagnostics>
        <trace autoflush="true" indentsize="4">
            <listeners>
                <remove name="Default" />
                <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" traceOutputOptions="DateTime,LogicalOperationStack,ThreadId" initializeData="trace.log" />
                <add name="RaygunTraceListener" type="Raygun.Diagnostics.RaygunTraceListener, Raygun.Diagnostics" />
            </listeners>
        </trace>
    </system.diagnostics>

Throughout my code I have many calls to Trace.TraceError() which when they are encountered do not seem to log anything to raygun.io. Do I have to do anymore for configuration above the standard .NET integration (instantiation of RaygunClient)?

**Comment by sirkirby** [comment]
You must also have the raygun configuration in your app.config as well. I would also recommend calling `Trace.TraceError()` instead of `Trace.WriteError()`.

```
<configuration>
  <section name="RaygunSettings" type="Mindscape.Raygun4Net.RaygunSettings, Mindscape.Raygun4Net" />
</configSections>
<RaygunSettings apikey="myAppKey" />
```

**Comment by jpierson** [comment]
Thanks, I'm using Trace.TraceError(). I've corrected my original post. Will try this and report back.

**Comment by jpierson** [comment]
Adding the API key specified in the config file seemed to do the trick. This has me wondering if there is a way to do the same through code.

**Comment by sirkirby** [comment]
yes, you can specify the key through code if you would like.
